accessControl:
  salt: gi2RbqVL70mBemKGgG2IqhbpFkX56ZBX
api:
  key: 6D15A345D5B14B688559116486A39372
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1653306600
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1646055600
      _plugins:
        read_until: 1655787600
      _releases:
        read_until: 1653386400
  discovery:
    upnpUuid: 44e9e6ae-d58f-41a3-84e2-b46bf0a824ef
  errortracking:
    unique_id: 5d6bbdb6-212e-4eca-9b31-192f6b33b3fb
  gcodeviewer:
    _config_version: 1
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: false
    unique_id: 4032a5f6-0b04-4f0b-9161-e4d117fcf911
  virtual_printer:
    _config_version: 1
    enabled: true
printerProfiles:
  default: _default
serial:
  autoconnect: true
  baudrate: 0
  port: AUTO
server:
  commands:
    serverRestartCommand: sudo systemctl restart octoprint
    systemRestartCommand: sudo reboot
    systemShutdownCommand: sudo poweroff
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  port: '5001'
  secretKey: 8jFzRnpRaTEKg4MBdIyP3xFMKxzpCEph
  seenWizards:
    backup: null
    corewizard: 4
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    name: PLA
webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://127.0.0.1:8082/?action=snapshot
  stream: http://192.168.1.50:8082/?action=stream
